const Map<String, String> ar = {
  'Skip': 'تخطي',
  'Language': 'اللغة',
  'Privacy': 'الخصوصية',
  'Sign up for an account': 'قم بالتسجيل للحصول على حساب تسجيل',
  'Sign Up': 'انشاء حساب',
  'Settings': 'الاعدادات',
  'My Account': 'حسابي',
  'Sing Up': 'تسجيل',
  'Dark Mode': 'الوضع الليلي',
  'Sign Out': 'تسجيل الخروج',
  'Sign In by google': 'تسجيل الدخول بجوجل',
  'Sign In by Facebook': 'تسجيل الدخول بفيسبوك',
  'Sign In': 'تسجيل الدخول',
  'Notifications': 'الاشعارات',
  'Search': 'بحث',
  'Follow': 'متابعه',
  'Loading...': '...تحميل',
  'Followers': 'متابعون',
  'Followings': 'اتابعه',
  'Suggested': 'مقترح',
  'Likes': 'تسجيلات الاعجاب',
  'Posts': 'المنشورات',
  'Videos': 'الفديوهات',
  'Following': 'اتابعه',
  'For You': 'لـــك',
  'Replay': 'رد',
  'Error': 'حدث خطأ ما',
  'Reactions': ' تفاعلات ',
  'Reaction': 'تفاعل',
  'Comments': ' تعليقات ',
  'Comment': ' تعليق ',
  'Shares': 'مشاركات',
  'ًWrite Your Post': 'اكتب منشورك',
  'Replies': 'ردود',
  'Uploading Reply...': '...جاري نشر الرد',
  'Can\'t Publish Empty Reply': 'لا يمكنك نشر رد فارغ',
  ' Write a Reply...': ' اكتب رد ',
  'Publish': 'نشر',
  'Video Description': 'وصف الفديو',
  'Create Post': 'انشاء منشور',
  'Name': 'الاسم',
  '@username': 'اسم المستخدم@',
  'Phone': 'تيليفون',
  'Birthday': 'تاريخ الميلاد',
  'The Comments': 'التعليقات',
  'Show': 'عرض',
  'Uploading Comment...': 'جاري نشر التعليق',
  'Can\'t Publish Empty Comment': 'لا يمكنك نشر تعليق فارغ',
  'Write a comment': 'اكتب تعليق',
  'Favorites': 'المفضله',
  'Remove this Follower': 'خدق هذه المتابعه',
  'Follow back': 'رد المتابعه',
  'UnFollow': 'الغاء المتابعه',
  'Save Video': 'حفظ الفديو',
  'Remove from Favorites': 'حذف من المفضله',
  'Add to Favorites': 'اضافه الي المفضله',
  'Report':'ايلاغ',
  'Not Interested':'غير مهتم',
  'Profile':'الملف الشخصي',
  'Upload your first Video':'حمل اول فديو لك',
  'Edit':'تعديل',
  'Delete This Video':'حذف هذا الفديو',
  'Yes':'نعم',
  'No':'لا',
  'Describe your video':'اوصف هذا الفديو',
};
