const Map<String, String> ar = {
  'Skip': 'تخطي',
  'Language': 'اللغة',
  'Privacy': 'الخصوصية',
  'Sign up for an account': 'قم بالتسجيل للحصول على حساب تسجيل',
  'Sign Up': 'انشاء حساب',
  'Settings': 'الاعدادات',
  'My Account': 'حسابي',
  'Sing Up': 'تسجيل',
  'Dark Mode': 'الوضع الليلي',
  'Sign Out': 'تسجيل الخروج',
  'Sign In by google': 'تسجيل الدخول بجوجل',
  'Sign In by Facebook': 'تسجيل الدخول بفيسبوك',
  'Sign In': 'تسجيل الدخول',
  'Notifications': 'الاشعارات',
  'Search': 'بحث',
  'Follow': 'متابعه',
  'Loading...': '...تحميل',
  'Followers': 'متابعون',
  'Followings': 'اتابعه',
  'Suggested': 'مقترح',
  'Likes': 'تسجيلات الاعجاب',
  'Posts': 'المنشورات',
  'Videos': 'الفديوهات',
  'Following': 'اتابعه',
  'For You': 'لـــك',
  'Replay': 'رد',
  'Error': 'حدث خطأ ما',
  'Reactions': ' تفاعلات ',
  'Reaction': 'تفاعل',
  'Comments': ' تعليقات ',
  'Comment': ' تعليق ',
  'Shares': 'مشاركات',
  'ًWrite Your Post': 'اكتب منشورك',
  'Replies': 'ردود',
  'Uploading Reply...': '...جاري نشر الرد',
  'Can\'t Publish Empty Reply': 'لا يمكنك نشر رد فارغ',
  ' Write a Reply...': ' اكتب رد ',
  'Publish': 'نشر',
  'Video Description': 'وصف الفديو',
  'Create Post': 'انشاء منشور',
  'Name': 'الاسم',
  '@username': 'اسم المستخدم@',
  'Phone': 'تيليفون',
  'Birthday': 'تاريخ الميلاد',
  'The Comments': 'التعليقات',
  'Show': 'عرض',
  'Uploading Comment...': 'جاري نشر التعليق',
  'Can\'t Publish Empty Comment': 'لا يمكنك نشر تعليق فارغ',
  'Write a comment': 'اكتب تعليق',
  'Favorites': 'المفضله',
  'Remove this Follower': 'خدق هذه المتابعه',
  'Follow back': 'رد المتابعه',
  'UnFollow': 'الغاء المتابعه',
  'Save Video': 'حفظ الفديو',
  'Remove from Favorites': 'حذف من المفضله',
  'Add to Favorites': 'اضافه الي المفضله',
  'Report': 'ايلاغ',
  'Not Interested': 'غير مهتم',
  'Profile': 'الملف الشخصي',
  'Upload your first Video': 'حمل اول فديو لك',
  'Edit': 'تعديل',
  'Delete This Video': 'حذف هذا الفديو',
  'Yes': 'نعم',
  'No': 'لا',
  'Describe your video': 'اوصف هذا الفديو',
  'Next': 'التالي',
  'Agree': 'أوافق',
  'New Model for Interact the video': 'نموذج جديد للتفاعل مع الفيديو',
  'The video screen split into Two parts Vertically for Positive or negative interaction.':
      'تم تقسيم شاشة الفيديو إلى قسمين عموديًا للتفاعل الإيجابي أو السلبي.',
  'User Data Security': 'أمان بيانات المستخدم',
  'You must make sure that your data is safe.':
      'يجب أن تتأكد من أن بياناتك آمنة',
  'All data is encrypted': "جميع البيانات مشفرة",
  'Privacy Policy': 'سياسة الخصوصية',
  'By tapping \"Agree\" you agree ': "بجرد النقر على \" أوافق \" فأنت توافق",
  'Terms of Service': 'شروط الخدمة',
  ' and acknowledge that you have read out ': "وتقر بأنك قد قرأت",
  'privacy Police': 'سياسة خاصة',
  ' to learn how to collect, use, and share your data.':
      "لمعرفة كيفية جمع واستخدام ومشاركة البيانات الخاصة بك.",
  'Dangerous organizations and individuals': 'المنظمات والأفراد الخطرين',
  'Illegal activity and regulated goods':
      "النشاط غير القانوني والسلع الخاضعة للرقابة",
  'Frauds and scams': "الاحتيال النصب",
  'Violent and graphic content': "محتوى عنيف ومصور",
  'Animal cruelty': 'القسوة على الحيوان',
  'Suicide, self-harm, and dangerous acts': "انتحار وإيذاء النفس وأعمال خطيرة",
  'Hate speech': 'خطاب الكراهية',
  'Harassment or bullying': "التحرش أو التنمر",
  'Pornography and nudity': "المواد الإباحية والعُري",
  'Minor safety': "سلامة طفيفة",
  'Spam': 'رسائل إلكترونية مزعجة',
  'Intellectual Property infringement': "التعدي على الملكية الفكرية",
  'Welcome to Smile Mobile App': 'Smile أهلا بك في تطبيق',
  'You can find Funny Videos or Posts':
      'يمكنك العثور على مقاطع فيديو أو منشورات مضحكة',
  'and You can Share your videos or posts':
      " كمايمكنك مشاركة مقاطع الفيديو أو المنشورات الخاصة بك",
  'Share': 'مشاركه',
  'Delete Video from Device': 'حذف الفديو من الجهاز',
  'Video Deleted successfully': 'تم حذف الفديو بنجاح',
  'Share Video Link': 'مشاركه رابط الفديو',
  'Save then Share Video': 'حفظ الفديو ثم مشاركته',
  'Field is required': 'الحقل مطلوب',
  'Enter valid email': 'أدخل بريد إلكتروني صالح',
  'this Email is Exist': "هذا البريد الإلكتروني موجود",
  'Username Must Start by "@"': '"@" يجب أن يبدأ اسم المستخدم ب ',
  'username length at least 5': "طول اسم المستخدم لا يقل عن 5",
  'username is Exist': "اسم المستخدم موجود",
  'password length at least 8': "طول كلمة المرور لا يقل عن 8",
  'password must has capital letter': "كلمة المرور يجب أن تحتوي على حرف كبير",
  'password must has small letter': "كلمة المرور يجب أن تحتوي على أحرف صغيرة",
  'password must has Numeric Number': "كلمة المرور يجب أن تحتوي على رقم رقمي",
  'Username not Exist': "اسم المستخدم غير موجود",
  'Username must Start with \'@\' Or Enter valid email':
      'اسم المستخدم يجب أن يبدأ بـ \" @ \ "أو أدخل بريدًا إلكترونيًا صالحًا',
  'Email  not Exist':"البريد الإلكتروني غير موجود",
  'Email or Username':'البريد الإلكتروني أو اسم المستخدم',
  'PassWord':'كلمة المرور',
  "OR":'أو',
  'Email':'البريد الالكتروني',
};
