const Map<String, String> en = {
  'Skip': 'Skip',
  'Language': 'Language',
  'Privacy': 'Privacy',
  'Sign up for an account': 'Sign up for an account',
  'Sign Up': 'Sign Up',
  'Settings': 'Settings',
  'My Account': 'My Account',
  'Sing Up': 'Sing Up',
  'Dark Mode': 'Dark Mode',
  'Sign Out': 'Sign Out',
  'Sign In by google': 'Sign In by google',
  'Sign In by Facebook': 'Sign In by Facebook',
  'Sign In': 'Sign In',
  'Notifications': 'Notifications',
  'Search': 'Search',
  'Follow': 'Follow',
  'Loading...': 'Loading...',
  'Followers': 'Followers',
  'Followings': 'Followings',
  'Suggested': 'Suggested',
  'Likes': 'Likes',
  'Posts': 'Posts',
  'Videos': 'Videos',
  'Following': 'Following',
  'For You': 'For You',
  'Replay': 'Replay',
  'Error': 'Error',
  'Reactions': ' Reactions ',
  'Reaction': ' Reaction ',
  'Comments': ' Comments ',
  'Comment': ' Comment ',
  'Shares': 'Shares',
  'ًWrite Your Post': 'ًWrite Your Post',
  'Replies': 'Replies',
  'Uploading Reply...': 'Uploading Reply...',
  'Can\'t Publish Empty Reply': 'Can\'t Publish Empty Reply',
  ' Write a Reply...': ' Write a Reply...',
  'Publish': 'Publish',
  'Video Description': 'Video Description',
  'Create Post': 'Create Post',
  'Name': 'Name',
  '@username': '@username',
  'Phone': 'Phone',
  'Birthday': 'Birthday',
  'The Comments': 'The Comments',
  'Show': 'Show',
  'Uploading Comment...': 'Uploading Comment...',
  'Can\'t Publish Empty Comment': 'Can\'t Publish Empty Comment',
  'Write a comment': 'Write a comment',
  'Favorites': 'Favorites',
  'Remove this Follower': 'Remove this Follower',
  'Follow back': 'Follow back',
  'UnFollow': 'UnFollow',
  'Save Video': 'Save Video',
  'Remove from Favorites': 'Remove from Favorites',
  'Add to Favorites': 'Add to Favorites',
  'Report': 'Report',
  'Not Interested': 'Not Interested',
  'Profile': 'Profile',
  'Upload your first Video': 'Upload your first Video',
  'Edit': 'Edit',
  'Delete This Video': 'Delete This Video',
  'Yes': 'Yes',
  'No': 'No',
  'Describe your video': 'Describe your video',
  'Next': 'Next',
  'Agree': 'Agree',
  'New Model for Interact the video': 'New Model for Interact the video',
  'The video screen split into Two parts Vertically for Positive or negative interaction.':
      'The video screen split into Two parts Vertically for Positive or negative interaction.',
  'User Data Security':'User Data Security',
  'You must make sure that your data is safe.':'You must make sure that your data is safe.',
      'All data is encrypted':'All data is encrypted',
  'Privacy Policy':'Privacy Policy',
  'By tapping \"Agree\" you agree ':'By tapping \"Agree\" you agree ',
  'Terms of Service':'Terms of Service',
  ' and acknowledge that you have read out ':' and acknowledge that you have read out ',
  'privacy Police':'privacy Police',
  ' to learn how to collect, use, and share your data.':' to learn how to collect, use, and share your data.',
  'Dangerous organizations and individuals':'Dangerous organizations and individuals',
  'Illegal activity and regulated goods':'Illegal activity and regulated goods',
  'Frauds and scams':'Frauds and scams',
  'Violent and graphic content':'Violent and graphic content',
  'Animal cruelty':'Animal cruelty',
  'Suicide, self-harm, and dangerous acts':'Suicide, self-harm, and dangerous acts',
  'Hate speech':'Hate speech',
  'Harassment or bullying':'Harassment or bullying',
  'Pornography and nudity':'Pornography and nudity',
  'Minor safety':'Minor safety',
  'Spam':'Spam',
  'Intellectual Property infringement':'Intellectual Property infringement',
  'Welcome to Smile Mobile App':'Welcome to Smile Mobile App',
  'You can find Funny Videos or Posts':'You can find Funny Videos or Posts',
  'and You can Share your videos or posts': 'and You can Share your videos or posts',
  'Share':'Share',
  'Delete Video from Device':'Delete Video from Device',
'Video Deleted successfully':'Video Deleted successfully',
  'Share Video Link':'Share Video Link',
  'Save then Share Video':'Save then Share Video',



};
