const Map<String, String> en = {
  'Skip': 'Skip',
  'Language': 'Language',
  'Privacy': 'Privacy',
  'Sign up for an account': 'Sign up for an account',
  'Sign Up': 'Sign Up',
  'Settings': 'Settings',
  'My Account': 'My Account',
  'Sing Up': 'Sing Up',
  'Dark Mode': 'Dark Mode',
  'Sign Out': 'Sign Out',
  'Sign In by google': 'Sign In by google',
  'Sign In by Facebook': 'Sign In by Facebook',
  'Sign In': 'Sign In',
  'Notifications': 'Notifications',
  'Search': 'Search',
  'Follow': 'Follow',
  'Loading...': 'Loading...',
  'Followers': 'Followers',
  'Followings': 'Followings',
  'Suggested': 'Suggested',
  'Likes': 'Likes',
  'Posts': 'Posts',
  'Videos': 'Videos',
  'Following': 'Following',
  'For You': 'For You',
  'Replay': 'Replay',
  'Error': 'Error',
  'Reactions': ' Reactions ',
  'Reaction': ' Reaction ',
  'Comments': ' Comments ',
  'Comment': ' Comment ',
  'Shares': 'Shares',
  'ًWrite Your Post': 'ًWrite Your Post',
  'Replies': 'Replies',
  'Uploading Reply...': 'Uploading Reply...',
  'Can\'t Publish Empty Reply': 'Can\'t Publish Empty Reply',
  ' Write a Reply...': ' Write a Reply...',
  'Publish': 'Publish',
  'Video Description': 'Video Description',
  'Create Post': 'Create Post',
  'Name': 'Name',
  '@username': '@username',
  'Phone': 'Phone',
  'Birthday': 'Birthday',
  'The Comments': 'The Comments',
  'Show': 'Show',
  'Uploading Comment...': 'Uploading Comment...',
  'Can\'t Publish Empty Comment': 'Can\'t Publish Empty Comment',
  'Write a comment': 'Write a comment',
  'Favorites': 'Favorites',
  'Remove this Follower': 'Remove this Follower',
  'Follow back': 'Follow back',
  'UnFollow': 'UnFollow',
  'Save Video': 'Save Video',
  'Remove from Favorites': 'Remove from Favorites',
  'Add to Favorites': 'Add to Favorites',
  'Report': 'Report',
  'Not Interested': 'Not Interested',
  'Profile': 'Profile',
  'Upload your first Video': 'Upload your first Video',
  'Edit': 'Edit',
  'Delete This Video': 'Delete This Video',
  'Yes': 'Yes',
  'No': 'No',
  'Describe your video':'Describe your video',
};
